import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="container-fluid sem-preenchimento">
          <div className="carousel slide" data-bs-ride="carousel" id="ads">
            <div className="carousel-indicators">
              <button
                className="active"
                data-bs-target="#ads"
                data-bs-slide-to="0"
              ></button>
              <button
                className=""
                data-bs-target="#ads"
                data-bs-slide-to="1"
              ></button>
              <button
                className=""
                data-bs-target="#ads"
                data-bs-slide-to="2"
              ></button>
            </div>
            <div className="carousel-inner">
              <div className="carousel-item active" data-bs-interval="4000">
                <img
                  src="image/portugal.jpg"
                  alt=""
                  className="d-block w-100"
                />
              </div>
              <div className="carousel-item" data-bs-interval="3000">
                <img
                  src="image/tailandia.jpg"
                  alt=""
                  className="d-block w-100"
                />
              </div>
              <div className="carousel-item" data-bs-interval="2000">
                <img
                  src="image/tropical.jpg"
                  alt=""
                  className="d-block w-100"
                />
                <div className="carousel-caption d-none d-md-block"></div>
              </div>
            </div>
            <button
              className="carousel-control-prev"
              data-bs-target="#ads"
              data-bs-slide="prev"
            >
              <span className="carousel-control-prev-icon"></span>
            </button>
            <button
              className="carousel-control-next"
              data-bs-target="#ads"
              data-bs-slide="next"
            >
              <span className="carousel-control-next-icon"></span>
            </button>
          </div>
        </div>

        <div class="container mt-5">
          <div class="row">
            <div class="col-md-6">
              <img src="image/aviao.png" alt="Imagem" class="img-fluid" />
            </div>
            <div class="col-md-6">
              <h2>Sobre nós</h2>
              <p>
                Bem-vindo à AgeTravel, a sua porta de entrada para aventuras e
                experiências incríveis em todo o mundo. Somos uma empresa de
                viagens dedicada a transformar os seus sonhos de viagem em
                realidade. Com décadas de experiência no setor, nosso
                compromisso é proporcionar a você as viagens mais memoráveis e
                sem preocupações.
              </p>
            </div>
          </div>
        </div>
        <div class="container mt-5">
          <div class="row">
            <div class="col-md-6 order-md-2">
              <img src="image/contato.png" alt="Imagem" class="img-fluid" />
            </div>
            <div class="col-md-6 order-md-1">
              <h2>Entre em contato</h2>
              <p>
                Atendimento Personalizado: Nossa equipe de especialistas em
                viagens está à sua disposição para criar itinerários
                personalizados que atendam aos seus desejos e necessidades.
              </p>
              <a href="contato.html" class="btn btn-info text-white">
                Clique aqui
              </a>
            </div>
          </div>
        </div>

        <div class="container mt-5">
          <div class="row">
            <div class="col-md-6">
              <img src="image/mapa.png" alt="Imagem" class="img-fluid" />
            </div>
            <div class="col-md-6">
              <h2>Conheça os nossos destinos</h2>
              <p>
                Destinos de Sonho: Escolha entre uma ampla variedade de
                destinos, desde praias de areias brancas no Caribe até as
                maravilhas culturais da Europa. Seja qual for o seu destino dos
                sonhos, temos opções para todos os gostos.
              </p>
              <a href="destino.html" class="btn btn-info text-white">
                Clique aqui
              </a>
            </div>
          </div>
        </div>
        <div class="container mt-5">
          <div class="row">
            <div class="col-md-6 order-md-2">
              <img src="image/promocao.png" alt="Imagem" class="img-fluid" />
            </div>
            <div class="col-md-6 order-md-1">
              <h2>Conheça as nossas promoções</h2>
              <p>
                Economia Incrível: Nossa promoção oferece descontos exclusivos
                em pacotes de viagem, voos e hospedagem. Assim, você pode
                economizar enquanto desfruta das férias dos seus sonhos.
              </p>
              <a href="promocao.html" class="btn btn-info text-white">
                Clique aqui
              </a>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
